### PR TITLE
Update to nodejs 0.12 and remove dependency on execSync

### PR DESCRIPTION
**Pull request by mikkeloscar**
This removes the dependency on the deprecated execSync and make limdu work with node 0.12.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
It's actually because it seems to be missing.

For instance it is used here: https://github.com/erelsgl/limdu/blob/master/utils/unseen_curves.js#L21 and here: https://github.com/erelsgl/limdu/blob/master/classifiers/multilabel/BinarySegmentation.js#L6

**Comment by erelsgl** [comment]
Thanks for noticing this. We are working on correcting this issue.

**Comment by vaskonov** [comment]
The dependencies were removed.

**Comment by erelsgl** [comment]
Thanks! But now 7 tests fail. Do you have any idea why?

**Pull request merged**
