### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kulakowka**
Added syntax highlighting in readme.md

### CODE REVIEW

**Comment by erelsgl** [comment]
Thanks for your contribution. The system says it cannot be merged because of conflicts. Do you know how to solve this?

**Comment by Berkmann18** [comment]
@erelsgl @kulakowka This can be solved by either clicking on the conflicted file and resolving the merge conflict here (on GH) or by rebasing the branch with master (using `git rebase master`).

**Comment by erelsgl** [comment]
This PR was made such a long time ago, that I do not remember what it was about and what is the best way to merge.. I think I will leave it like this (unless someone else wants to merge)

**Comment by Berkmann18** [comment]
@erelsgl You can see what it's about looking https://github.com/erelsgl/limdu/pull/32/files (which from what I understood was: reformating and some other stuff).

And unless you're not the only one with write permissions, no one else could merge it.
As for the fixing the conflict only the maintainers, members (applicable for only organisations) and collaborators (like organisation members but who are outside of the organisation).

**Pull request closed without merging**
