### PR TITLE
Release improvement

### PR DESCRIPTION
**Pull request by Berkmann18**
IMO, you should use a CI or [GitHub Action](https://github.com/marketplace?category=deployment&query=npm&type=actions) to at least automatically release new versions (or better use a comment convention like Angular and let `semantic-release` do the version bumping and release for you), especially as the version on NPM is two patches behind.

With this PR, you'll still need to manually run `npm publish`, but at least the version should be up-to-date with the changes from my previous PR.

### CODE REVIEW

**Comment by erelsgl** [comment]
This sounds like a good idea, but I am not sure how to start.

**Comment by Berkmann18** [comment]
Would you instead use an *external CI/CD* service like TravisCI/CircleCI or what is more *native to GH* with Actions like https://github.com/Berkmann18/lh-avg/blob/master/.github/workflows/semantic-release.yml (this uses the [following config](https://github.com/Berkmann18/lh-avg/blob/master/.releaserc) and expects commits to follow https://www.conventionalcommits.org/en/v1.0.0)?
You could even try [Rolling Versions](https://rollingversions.com/help/github-actions), which is apparently a more interactive/user-involved approach (I've not tried that one since I spoke to the creator who wrote a Medium article about that tool).
I can help you set up the sytem.

**Comment by erelsgl** [comment]
Github Actions sounds like a better option. I will be happy for help. Can we schedule a Zoom meeting?

**Comment by Berkmann18** [comment]
Sure, do you have a calendar I could put an invite to? I'm generally free from, 12-1pm, 5pm-onwards (GMT) on weekdays (aside for Tuesdays, where I'm only free after 8:30pm) and any time on weekends (with exceptions as I have events on some weekends).

**Comment by erelsgl** [comment]
Hi. Would you like to meet today (Wed.) at 12 PM GMT?

**Comment by Berkmann18** [comment]
Just seen this, I had a hectic week. What other day/time could you do?

**Comment by erelsgl** [comment]
How about today (Sunday), 12pm gmt?

**Comment by erelsgl** [comment]
I do not have a public calendar, but I am available at Mondays most of the day, so we can schedule a time in the coming Monday.

**Comment by Berkmann18** [comment]
Sure, Monday 19th from 6pm (UK time) is good for me.

**Pull request merged**
